language: node_js
node_js:
- 6.10.0
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: pyqeLUoHNg0frvNMnn60tP3kYmto6fMroz6HkuTr8KED982+ageqU2Vv8BAt/4S5S0938vHrt2saf1MwL/nGfOr0AGe1d9yzSbrtVoTx8dmW/+KTyGGcNBFxOfWZvPMaSKpbWlxTIUn3CASUnUuRD5jAHH7suA87i5lSH2YpVlX/JXKsbXzPFIwPDQhZhHteTp2FYEN7azMXSCWPKREue7PX8fOVnJQtAwKHG+em/1TxVfc4U1sjZxqDSqzlfmSNPJLxDon0oE1mmac0ZIVLJWDXv86a92sicYxr29KEEpAY+R9HICFb6i8XbgjD+uC1XO7aXmSRK7wAQfjySoykAQ0V3hnWyhGEeRf6UNAj6LHhf1ZINU6i3mXHPTQ11tzpfCaEdec0ERksXZ+RbbQuLwut5oCCzvggQy5bQSYQkrUBAN+VrlhYDcf14ATwwdAcgCmgkep2Zcj+kyM6lLVUec+gEotZXBllj1ACjTy4jH7VgDBSOslYy/Tor6u3ctVQoQmdmF4DAIOpQ9iQyTo6jR0citFmgOkIdqmbgYFP1j0CfgyG/0SxQTGnE0MbuRoWG9dEZOeCRHuKZplDr8EJwBRM7pSXLphwmBoB1+LqGEwefvcZ9VUF1P1x/yMmq+WHv38OFyPmTAppNfWvC7IkA60ZPkO34jzi+WyI0KpV8d4=
  app: gx-blog
  on:
    repo: emagrorrim/my-blog
